CREATE TABLE NOTICE
(
	NOTICE_NO	NUMBER NOT NULL PRIMARY KEY,
	TITLE VARCHAR2(100 BYTE),
	CONTENT VARCHAR2(100 BYTE),
	HIT NUMBER,
	CREATED TIMESTAMP,
	LASTMODIFIED TIMESTAMP
);

CREATE SEQUENCE NOTICE_SEQ NOCACHE;

INSERT INTO NOTICE VALUES(1, '공지사항1', '내용1', 0, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO NOTICE VALUES(2, '공지사항2', '내용2', 0, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO NOTICE VALUES(3, '공지사항3', '내용3', 0, SYSTIMESTAMP, SYSTIMESTAMP);