CREATE TABLE GALLERY(
	GALLERY_NO NUMBER PRIMARY KEY NOT NULL,
	WRITER VARCHAR2(50 BYTE),
	TITLE VARCHAR2(100 BYTE),
	CONTENT VARCHAR2(100 BYTE),
	IP VARCHAR2(30 BYTE),
	HIT NUMBER,
	CREATED DATE,
	MODIFIED DATE	
);

DROP TABLE FILE_ATTACH;


CREATE TABLE FILE_ATTACH(
	FILE_ATTACH_NO NUMBER PRIMARY KEY NOT NULL,
	PATH VARCHAR2(300 BYTE),
	ORIGIN VARCHAR2(300 BYTE),
	SAVED VARCHAR2(40 BYTE),
	DOWNLOAD_CNT NUMBER,
	GALLERY_NO NUMBER
);


ALTER TABLE FILE_ATTACH ADD CONSTRAINT FILE_ATTACH_GALLERY_FK FOREIGN KEY(GALLERY_NO) REFERENCES GALLERY (GALLERY_NO) ON DELETE CASCADE;

CREATE SEQUENCE GALLERY_SEQ NOCACHE;
CREATE SEQUENCE FILE_SEQ NOCACHE;