CREATE TABLE EMP
(
    NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    DEPT VARCHAR2(20),
    SALARY NUMBER,
    HIRED VARCHAR2(10)
);

CREATE SEQUENCE EMP_SEQ NOCACHE;

INSERT INTO EMP(NO, NAME, DEPT, SALARY, HIRED) VALUES(EMP_SEQ.NEXTVAL, '이정재', '총무', 5000, '2022-04-20');